name: Main Action
on: workflow_dispatch

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    outputs:
      hoge: ${{ steps.step-hoge.outputs.hoge }}
      fuga: ${{ steps.step-fuga.outputs.fuga}}
    env:
      HOGE: "hogeOutput"
      FUGA: "fugaOutput"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call Hello World
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/echo
          args: Hello, World From Job1!

      - id: step-hoge
        run: echo "::set-output name=hoge::$(echo $HOGE)"

      - id: step-fuga
        run: echo "::set-output name=fuga::$(echo $FUGA)"

  job2:
    name: JOB2
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call Hello World
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/echo
          args: Hello, World From Job2!

      - name: Show Shared Variables From Job1!
        run: |
          echo ${{ needs.job1.outputs.hoge }}
          echo ${{ needs.job1.outputs.fuga }}
